name: Collection release and publish
on:
  release:
    types: [published]

jobs:
  publish-collection-artifact:
    name: Publish
    runs-on: ${{ matrix.runner-os }}
    strategy:
      matrix:
        runner-os:
          - ubuntu-16.04
        ansible-version:
          - git+https://github.com/ansible/ansible.git@devel
        runner-python-version:
          - 3.7
    steps:

      - name: Check out ${{ github.repository }} on disk
        uses: actions/checkout@master

      - name: Set up Python ${{ matrix.runner-python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.runner-python-version }}

      - name: Install Ansible ${{ matrix.ansible-version }}
        run: >-
          python -m pip install --user '${{ matrix.ansible-version }}' -r contrib/publish-requirements.txt

      - name: Generate a version from tag
        run: >-
          ./contrib/publish.sh ${GITHUB_REF##*/}
        env:
          API_GALAXY_TOKEN: 'some_random' #${{ secrets.API_GALAXY_TOKEN }}
